### PR TITLE
Better strict-d3

### PR DESCRIPTION
**Pull request by etpinard**
Use `strict_d3` browserify transform instead of injection `strict-d3.js` IIFE.

See https://github.com/plotly/plotly.js/pull/1871/commits/e84701f75ac30e093dfcb73341a3ec472b8643da

### CODE REVIEW

**Comment by etpinard** [comment]
@rreusser ok to merge?

**Comment by rreusser** [comment]
👍 💃

**Comment by rreusser** [comment]
Published and updated on the website

**Comment by rreusser** [comment]
FWIW I'm 150% glad to review, but if you need a quick merge + publish, I think you're on the npm repo, so you're also welcome to bump the version, `npm run build` to update the site, and publish. Maybe `build` should be a prepublish script or something…

**Pull request merged**
